micronaut:
    application:
        name: service-b
    server:
        port: 8081
tracing:
    jaeger:
        enabled: true
        sampler:
            probability: 1.0
        service-name: my-micronaut-app
        udp-sender:
            hostname: localhost
            port: 6831
