micronaut:
    application:
        name: service-a
tracing:
    jaeger:
        enabled: true
        reporter:
            log-spans: true
        sampler:
            probability: 1.0
        service-name: service-a
        udp-sender:
            hostname: localhost
            port: 6831
